# Generated by Django 3.0.7 on 2020-06-16 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('surname', models.CharField(max_length=25)),
                ('address', models.CharField(blank=True, max_length=25)),
                ('city_birthday', models.CharField(blank=True, max_length=25)),
                ('date_birthday', models.DateField()),
                ('start_work', models.DateField()),
            ],
        ),
    ]
